### ISSUE TITLE
有外部依赖项的组件调用时报错

### ISSUE THREAD

**Issue by RoseShao** [jiangwei58/papayaui#4]
我的项目是以npm方式安装，如您教程所写安装使用，也安装了 async-validator dayjs这两个插件。但是，如pa-calendar这样的组件，在调用时会报dayjs错误，不知是什么原因，请大佬看下，感谢！我的项目地址https://github.com/RoseShao/demo-papayaui/tree/master

**Comment by yahahanihao** [comment]
> 我的项目是以npm方式安装，如您教程所写安装使用，也安装了 async-validator dayjs这两个插件。但是，如pa-calendar这样的组件，在调用时会报dayjs错误，不知是什么原因，请大佬看下，感谢！我的项目地址https://github.com/RoseShao/demo-papayaui/tree/master

能提供一下具体的错误信息，还有运行平台（如小程序、h5）吗？

**Comment by jiangwei58** [comment]
> 我的项目是以npm方式安装，如您教程所写安装使用，也安装了 async-validator dayjs这两个插件。但是，如pa-calendar这样的组件，在调用时会报dayjs错误，不知是什么原因，请大佬看下，感谢！我的项目地址https://github.com/RoseShao/demo-papayaui/tree/master

@RoseShao 尝试在main.js里引入dayjs

**Comment by RoseShao** [comment]
> > 我的项目是以npm方式安装，如您教程所写安装使用，也安装了 async-validator dayjs这两个插件。但是，如pa-calendar这样的组件，在调用时会报dayjs错误，不知是什么原因，请大佬看下，感谢！我的项目地址https://github.com/RoseShao/demo-papayaui/tree/master
> 
> @RoseShao 尝试在main.js里引入dayjs

解决了，确实可以，感谢！
